[package]
name = "beholder"
version = "0.1.0"
edition = "2021"

[lib]
name = "beholder"
path = "src/lib.rs"

[[bin]]
name = "beholder"
path = "src/main.rs"

[dependencies]
deku = "0.16.0"
flate2 = "1.0.27"
lz4_flex = "0.11.1"
lzzzz = "1.0.4"
